@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Init ==
BaseOpMode --> MecanumDrive: construct
BaseOpMode --> ViperDrive: construct
BaseOpMode --> LiftDrive: construct
BaseOpMode --> LiftDrive: setViperDrive
BaseOpMode --> IntakeDrive: construct
BaseOpMode --> WristDrive: construct
BaseOpMode --> WristDrive: setIntakeDrive
BaseOpMode --> Telemetry: update

== Start ==
BaseOpMode --> BaseOpMode: Add DebugAction
BaseOpMode --> ViperDrive: limits()
BaseOpMode --> ViperLimitDrive: addListener()
BaseOpMode --> LiftDrive: limits()
BaseOpMode --> LiftDrive: adjustViperLimits()
BaseOpMode --> LiftLimitDrive: addListener()
BaseOpMode --> BaseOpMode: updateRunningActions()
BaseOpMode --> Telemetry: update

== Stop ==
BaseOpMode --> BaseOpMode: clear Running Actions
BaseOpMode --> Telemetry: update
BaseOpMode --> PoseStorage: remember current pose

@enduml